### ISSUE TITLE
Suggestion: Add Cold Resistance true/false for each backpack

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#14]
Some people might want to tweak if backpacks protect from cold.

**Comment by sbtoonz** [comment]
This is something I will probably opt out of

**Comment by thedefside** [comment]
@sbtoonz you don't want it in the mod, or you don't want to do it? I would be willing to do the work. I submitted a PR for JotunnBackpacks to apply proper frost resistance, but obviously that mod is not being updated.

https://github.com/Emrik-North/JotunnBackpacks/pull/14

**Comment by sbtoonz** [comment]
This might be an unpopular view point 

You're already gaining a TON out of the bag
1) Dynamic inventory
2) Inventory that increases with bag level
3) Movement speed impact (if configured) 


I feel like adding stuff like frost resist to things that only cover a portion of the players back is ...well it kind of makes my OCD go through the roof. If I am out hiking in the mountains there is no way in heck my bag is keeping me very warm at all 
My arms need to be covered for that 
Sometimes my bag even makes me colder due to the sweat on the back and the cold outside

So I just have a hard time accepting the concept into the mod essentially.

**Comment by lupuleasa-core** [comment]
that is fine with me, no cold resist is fitting

it would actually give a good use for wolf chest armor

**Comment by lupuleasa-core** [comment]
yep, the new update is looking sleek

thank you toonz for the great work

I will be looking forward to the configs for move speed penalty and backpack weight reduction % as in our next playthrough I want backpacks to be an alternative for being slower, but being able to carry more stuff. Right now backpacks in the mod only add slot volume, and not extra weight.

Basically 3 configs would cover all cases:
- Backpack speed penalty (from -100 to 0)
- Backpack weight reduction (for items inside)
- Backpack carry weight bonus (like meginjord buff)

**Comment by sbtoonz** [comment]
This is already done

**Comment by lupuleasa-core** [comment]
Another interesting idea, but unsure how doable it is:

Having the movespeed penalty be scaling with the percentage of how FULL the backpack is. That would be really cool tbh, but maybe engine does not support.

Like an empty backpack is 0% move loss.

A full backpack with its weight reduced is -30% speed

**Comment by lupuleasa-core** [comment]
oh, then I have not cleared the configs then, thanks

**Comment by sbtoonz** [comment]
> oh, then I have not cleared the configs then, thanks
> 
> 

V0.0.9 on thunder store has all charges

**Comment by lupuleasa-core** [comment]
yep, I took that one, but didn't clear the configs

**Comment by lupuleasa-core** [comment]
used the auto-update feature
