### ISSUE TITLE
Suggestion: Show in backpack tooltip how much weight reduction a bag has

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#21]
Unsure if engine supports it, but if I have configured -50% carry weight reduction it would be great for other people on my server to find that out by having some text in the backpack tooltip here.
![image](https://user-images.githubusercontent.com/5671120/154474389-4bf76bd7-09b5-4b91-9417-bf57b1965de4.png)

Right now it shows the move speed reduction, and a hint on how to open backpack with Shift+E, which is great!

**Comment by sbtoonz** [comment]
I gotta think on this one and understand a little bit how the tooltips poll their data in valheim 

there is potential to hook into that function and alter the text

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/154518387-14f87a1c-9fba-4ac9-9b96-a440f93f1160.png)

**Comment by lupuleasa-core** [comment]
just call it

"Contents weight reduction: X%"

**Comment by MAA-Alastair** [comment]
Two ways you can try to implement it, which is via weight reduction, or you do what the mod Judes Equipment by GoldenJude does, which instead of making weight reduction, it actually just increases the carry weight capacity on your character overall. The heavy backpack they have increases your carry weight limit up to 200 rather than having the additional inventory space though.
![image](https://user-images.githubusercontent.com/99830719/154519519-be47505c-67d5-4f2d-b268-0ab055940d9d.png)

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/154520231-2d8dca85-d1e0-4d47-81c2-5bb0dc56107f.png)
