### ISSUE TITLE
Fine backpack has so many slots it has a scrollbar

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/BackPacks_Remake#30]
I think the upgraded backpacks have enough space, so it would be fine to shave some slots until no scroll is needed.

Rugged backpack starts with 2 slots

Normal should start with 4

Fine should start with 6 or 8

That balancing would make it better tbh

But yeah, main point is that scrollbar shouldn't be needed

**Comment by RapidHabit** [comment]
A config option to adjust bag size (both slots on initial craft as well as per upgrade) would be a nice feature.  I agree with lululeasa that the silver bag has far too many slots (in my opinion).  Id prefer to adjust the setting so that at most a fully upgraded top tier bag would offer equal slots to a full player inventory).

**Comment by sbtoonz** [comment]
It’s already there

**Comment by RapidHabit** [comment]
@sbtoonz, Would you point me to the config item that controls this? it's not clear to me from the description which line items control the slot sizes.

**Comment by sbtoonz** [comment]
![image](https://user-images.githubusercontent.com/67915879/155617545-3ae5a462-6d83-440c-ac0d-46c3369dcc5c.png)

**Comment by RapidHabit** [comment]
Thanks sbtoonz!
I never realized the dimensions were for bag slots.  I assumed they were for positioning of the bag inventory graphics.  I appreciate you taking the time to point this out for me.
