### ISSUE TITLE
 2.4 last night.  backpacks are still a little buggy 

### ISSUE THREAD

**Issue by sbtoonz** [sbtoonz/BackPacks_Remake#34]
tested version 2.4 last night. 
 backpacks are still a little buggy but worked without the need to re-equip.  

- we found that in multiplayer instances if another player is performing an action nearby while a player is opening their backpack the backpack will bug and not open during the period the other player is performing their action.  
- If the other player stops their current action however, the player attempting to open their bag will be able to open the bag successfully.  
- Once the bag is open, the other player can begin performing their actions again without impacting the player migrating items to their bag etc.   

As an example: at one point last night one player (player A) was attempting to mine iron ore while another (Player B) was attempting to open their bag and move their ore to the backpack.  The backpack would not open for Player B until Player A stopped mining ore and waited.  Once the bag was open however, Player A could begin mining again while Player B moved items around in his inventory.

_Originally posted by @RapidHabit in https://github.com/sbtoonz/BackPacks_Remake/issues/32#issuecomment-1050831715_

**Comment by sbtoonz** [comment]
@tigue 
I have posted your issue as a new one and will work to correct

**Comment by sbtoonz** [comment]
@rapidhabit can you supply any logs of this issue, I have no other people to test multiplayer problems with

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/Test
can you try this version @rapidhabit

**Comment by RapidHabit** [comment]
Please let me know where to pull logs from and I'll happily supply what I can.  I've downloaded the test version and input it on the server.  I'll pass it along the others tonight and we'll give it a try this evening.

**Comment by sbtoonz** [comment]
in your bepinex folder there is a LogOutput.log file

**Comment by sbtoonz** [comment]
it will get populated  for every game session

**Comment by RapidHabit** [comment]
Noted!  unfortunately i was on solo this morning already so it appears to have been repopulated.  we will test the bags tonight using the latest backpack update and I'll ensure I grab a copy of the log regardless of whether its now operating properly or not.

**Comment by RapidHabit** [comment]
just noticed that with the latest 'test' build, i flipped between two different worlds (one solo/client only and then onto our multiplayer server) - upon joining the multiplayer server and opening a chest, the chest showed no slots just the background of the inventory.  Additionally once this happened I couldnt move, interact or do anything in game and was forced to Alt+F4 to exit.  I tested this a few times, When joining the first world everything works fine, but upon jumping to another world it would occur immediately upon opening a chest.  I looked at bepinex and it responds normally - no errors or anything indicating this is happening (i had it up on my second monitor) - it even registers the commands im performing in game (such as pressing E to try to close the chest etc.  Upon flipping back to 2.4 and testing again i havent run into this problem....

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/0.2.4B_test

**Comment by RapidHabit** [comment]
applying now and should be able to test momentarily

**Comment by sbtoonz** [comment]
Yes it is a configuration flag in the test version :D Will check this log thanks for attaching

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/commit/7a74c29f9a2c6d2fcfc56cf6c35513f607840c94

**Comment by sbtoonz** [comment]
This is my last pending issue before pushing another release candidate version I have changed the technique of looking for key press from using unity native code to using valheims input system

Hopefully this will quell the issue you are facing as I see nothing wonky in your logs. Curious what the other player log looks like whilst they are performing said action and you cannot open 
also curious of server log

**Comment by sbtoonz** [comment]
https://github.com/sbtoonz/BackPacks_Remake/releases/tag/V0.2.5B

**Comment by sbtoonz** [comment]
please test and report back if the opening while interacting issues are solved or curbed at all

**Comment by RapidHabit** [comment]
Will do

**Comment by RapidHabit** [comment]
Sorry for the delay, the patch really hosed us up for a day.  We just tested the backpacks using the latest test version.  The issue still exists where if one person opens their backpack the other often cannot.  In some cases the other can open their backpack but if the two backpacks arent the same, as is the case now where Player 2 has a rugged (upgraded to second level) backpack and I have a Silver (no upgrades) backpack we found that opening the corresponding pack shows the slots of the other persons pack but only to the level of 'your' current pack.  So for example, he opened his pack, then I opened mine.  mine opened but showed 8 slots (since my normal bag is not upgraded) - I then reequiped my pack and opened it after which he opened his pack and showed 35 slots (so a tier 2 version of the silver pack) even though he was using a rugged pack....

most times the pack itself wont open which is what initially happened when we tried.  the fix when that happens is to unequip the pack and reequip. 

Hopefully these logs will help with identifying the issue.
[LogOutput - Player 2.log](https://github.com/sbtoonz/BackPacks_Remake/files/8172156/LogOutput.-.Player.2.log)
[LogOutput - Server.log](https://github.com/sbtoonz/BackPacks_Remake/files/8172157/LogOutput.-.Server.log)
[LogOutput - Player 1.log](https://github.com/sbtoonz/BackPacks_Remake/files/8172158/LogOutput.-.Player.1.log)
.

**Comment by RapidHabit** [comment]
In addition, at times the pack itself seems to become a 'bag of holding' in that it will store unlimited amounts of items without affecting the total weight.  I currently have our config setup so that all items placed in the bag are stored at 40% of their normal weight (so an item that normally weighs 10lbs now weighs 4lbs).  this seems to work more often than not but we've run into a few instances where we were able to continuously gather heavier items - like ore, place them in our bag and the bag held the items but did not adjust our overall weight at all.   This led to being able to carry 4-5 stacks of ore in one trip even though we should not have been able to (as is the case in most instances)...

**Comment by RapidHabit** [comment]
One more item - it occasionally eats resources from your bag (they go into the void apparently).

**Comment by sbtoonz** [comment]
im not sure i will have to ponder on this because there is no way the code running on your client could impact another player at this junction

**Comment by RapidHabit** [comment]
understood.  it was/is very interesting.  we're also finding the bags seem to eat loot quite often since the last patch.

**Comment by sbtoonz** [comment]
I just spent 2 hours on my laptop and desktop and cannot replicate this behavior

which is odd cuz your modlist is really small
